### ISSUE TITLE
unable to build 0.15.9

### ISSUE THREAD

**Issue by anthraxx** [cobalt-org/cobalt.rs#731]
Hi, looks like I cant build cobalt with sass:

```
cargo build --release --locked --features 'syntax-highlight sass'
```

This also happens without adding --features 'syntax-highlight'

Maybe you have an idea whats wrong?

```
==> Starting build()...
    Updating crates.io index
 Downloading crates ...
  Downloaded walkdir v2.3.1
  Downloaded exitfailure v0.5.1
  Downloaded deunicode v1.0.0
  Downloaded env_logger v0.7.1
  Downloaded failure v0.1.6
  Downloaded itertools v0.8.2
  Downloaded log v0.4.8
  Downloaded lazy_static v1.4.0
  Downloaded notify v4.0.15
  Downloaded regex v1.3.4
  Downloaded liquid v0.19.0
  Downloaded ignore v0.4.11
  Downloaded clap v2.33.0
  Downloaded serde_yaml v0.8.11
  Downloaded serde_json v1.0.47
  Downloaded toml v0.5.6
  Downloaded serde v1.0.104
  Downloaded chrono v0.4.10
  Downloaded syntect v3.2.0
  Downloaded jsonfeed v0.2.0
  Downloaded ghp v0.1.2
  Downloaded sitemap v0.4.0
  Downloaded sass-rs v0.2.2
  Downloaded normalize-line-endings v0.3.0
  Downloaded time v0.1.42
  Downloaded ansi_term v0.11.0
  Downloaded termcolor v1.1.0
  Downloaded textwrap v0.11.0
  Downloaded bitflags v1.2.1
  Downloaded tiny_http v0.6.2
  Downloaded thread_local v1.0.1
  Downloaded num-integer v0.1.42
  Downloaded vec_map v0.8.1
  Downloaded aho-corasick v0.7.8
  Downloaded mio-extras v2.0.6
  Downloaded liquid-compiler v0.19.0
  Downloaded liquid-value v0.19.1
  Downloaded liquid-error v0.19.0
  Downloaded backtrace v0.3.43
  Downloaded onig v4.3.3
  Downloaded xml-rs v0.8.0
  Downloaded url v2.1.1
  Downloaded serde_derive v1.0.104
  Downloaded itoa v0.4.5
  Downloaded globset v0.4.4
  Downloaded rss v1.9.0
  Downloaded atty v0.2.14
  Downloaded strsim v0.8.0
  Downloaded pulldown-cmark v0.6.1
  Downloaded regex-syntax v0.6.14
  Downloaded liquid-interpreter v0.19.0
  Downloaded getopts v0.2.21
  Downloaded memchr v2.3.0
  Downloaded crossbeam-channel v0.4.0
  Downloaded lazycell v1.2.1
  Downloaded inotify v0.7.0
  Downloaded ryu v1.0.2
  Downloaded mio v0.6.21
  Downloaded libc v0.2.66
  Downloaded dtoa v0.4.5
  Downloaded flate2 v1.0.13
  Downloaded yaml-rust v0.4.3
  Downloaded either v1.5.3
  Downloaded unicode-width v0.1.7
  Downloaded failure_derive v0.1.6
  Downloaded cfg-if v0.1.10
  Downloaded same-file v1.0.6
  Downloaded humantime v1.3.0
  Downloaded filetime v0.2.8
  Downloaded linked-hash-map v0.5.2
  Downloaded doc-comment v0.3.1
  Downloaded fnv v1.0.6
  Downloaded num-traits v0.2.11
  Downloaded plist v0.4.2
  Downloaded error-chain v0.10.0
  Downloaded unicode-segmentation v1.6.0
  Downloaded url v1.7.2
  Downloaded liquid-derive v0.19.0
  Downloaded bincode v1.2.1
  Downloaded pest_derive v2.1.0
  Downloaded synstructure v0.12.3
  Downloaded crossbeam-utils v0.7.0
  Downloaded rustc-demangle v0.1.16
  Downloaded quick-error v1.2.3
  Downloaded pest v2.1.2
  Downloaded proc-macro2 v1.0.8
  Downloaded bstr v0.2.11
  Downloaded backtrace-sys v0.1.32
  Downloaded net2 v0.2.33
  Downloaded proc-quote v0.2.2
  Downloaded base64 v0.10.1
  Downloaded line-wrap v0.1.1
  Downloaded miniz_oxide v0.3.6
  Downloaded crc32fast v1.2.0
  Downloaded anymap v0.12.1
  Downloaded syn v1.0.14
  Downloaded idna v0.1.5
  Downloaded chrono_utils v0.1.3
  Downloaded onig_sys v69.1.0
  Downloaded percent-encoding v2.1.0
  Downloaded slab v0.4.2
  Downloaded iovec v0.1.4
  Downloaded inotify-sys v0.1.3
  Downloaded percent-encoding v1.0.1
  Downloaded proc-macro2 v0.4.30
  Downloaded walkdir v0.1.8
  Downloaded ascii v0.8.7
  Downloaded autocfg v1.0.0
  Downloaded syn v0.15.44
  Downloaded unicase v2.6.0
  Downloaded quote v1.0.2
  Downloaded matches v0.1.8
  Downloaded idna v0.2.0
  Downloaded byteorder v1.3.4
  Downloaded derive_builder v0.9.0
  Downloaded sass-sys v0.4.17
  Downloaded unicode-xid v0.1.0
  Downloaded unicode-bidi v0.3.4
  Downloaded safemem v0.3.3
  Downloaded version_check v0.9.1
  Downloaded pest_generator v2.1.1
  Downloaded ucd-trie v0.1.2
  Downloaded unicode-normalization v0.1.12
  Downloaded cc v1.0.50
  Downloaded winapi v0.2.8
  Downloaded kernel32-sys v0.2.2
  Downloaded unicode-xid v0.2.0
  Downloaded pkg-config v0.3.17
  Downloaded adler32 v1.0.4
  Downloaded proc-quote-impl v0.2.2
  Downloaded quote v0.6.13
  Downloaded proc-macro-hack v0.5.11
  Downloaded autocfg v0.1.7
  Downloaded num_cpus v1.12.0
  Downloaded darling v0.10.2
  Downloaded pest_meta v2.1.2
  Downloaded smallvec v1.2.0
  Downloaded winapi-build v0.1.1
  Downloaded chunked_transfer v0.3.1
  Downloaded darling_core v0.10.2
  Downloaded darling_macro v0.10.2
  Downloaded maplit v1.0.2
  Downloaded ident_case v1.0.1
  Downloaded strsim v0.9.3
  Downloaded quick-xml v0.17.2
  Downloaded encoding_rs v0.8.22
  Downloaded derive_builder_core v0.9.0
   Compiling libc v0.2.66
   Compiling proc-macro2 v1.0.8
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.14
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling serde v1.0.104
   Compiling cc v1.0.50
   Compiling memchr v2.3.0
   Compiling lazy_static v1.4.0
   Compiling log v0.4.8
   Compiling pkg-config v0.3.17
   Compiling fnv v1.0.6
   Compiling proc-macro2 v0.4.30
   Compiling smallvec v1.2.0
   Compiling matches v0.1.8
   Compiling bitflags v1.2.1
   Compiling unicode-xid v0.1.0
   Compiling ucd-trie v0.1.2
   Compiling byteorder v1.3.4
   Compiling strsim v0.9.3
   Compiling either v1.5.3
   Compiling ident_case v1.0.1
   Compiling regex-syntax v0.6.14
   Compiling maplit v1.0.2
   Compiling rustc-demangle v0.1.16
   Compiling syn v0.15.44
   Compiling ryu v1.0.2
   Compiling liquid-error v0.19.0
   Compiling autocfg v0.1.7
   Compiling winapi-build v0.1.1
   Compiling encoding_rs v0.8.22
   Compiling version_check v0.9.1
   Compiling crc32fast v1.2.0
   Compiling quick-error v1.2.3
   Compiling unicode-width v0.1.7
   Compiling failure_derive v0.1.6
   Compiling same-file v1.0.6
   Compiling anymap v0.12.1
   Compiling xml-rs v0.8.0
   Compiling slab v0.4.2
   Compiling winapi v0.2.8
   Compiling safemem v0.3.3
   Compiling percent-encoding v1.0.1
   Compiling lazycell v1.2.1
   Compiling adler32 v1.0.4
   Compiling itoa v0.4.5
   Compiling derive_builder v0.9.0
   Compiling doc-comment v0.3.1
   Compiling pulldown-cmark v0.6.1
   Compiling linked-hash-map v0.5.2
   Compiling percent-encoding v2.1.0
   Compiling chunked_transfer v0.3.1
   Compiling ascii v0.8.7
   Compiling strsim v0.8.0
   Compiling unicode-segmentation v1.6.0
   Compiling dtoa v0.4.5
   Compiling ansi_term v0.11.0
   Compiling deunicode v1.0.0
   Compiling termcolor v1.1.0
   Compiling vec_map v0.8.1
   Compiling normalize-line-endings v0.3.0
   Compiling unicode-bidi v0.3.4
   Compiling thread_local v1.0.1
   Compiling textwrap v0.11.0
   Compiling getopts v0.2.21
   Compiling line-wrap v0.1.1
   Compiling walkdir v2.3.1
   Compiling humantime v1.3.0
   Compiling pest v2.1.2
   Compiling miniz_oxide v0.3.6
   Compiling itertools v0.8.2
   Compiling unicode-normalization v0.1.12
   Compiling yaml-rust v0.4.3
   Compiling kernel32-sys v0.2.2
   Compiling walkdir v0.1.8
   Compiling aho-corasick v0.7.8
   Compiling bstr v0.2.11
   Compiling ghp v0.1.2
   Compiling idna v0.1.5
   Compiling idna v0.2.0
   Compiling base64 v0.10.1
   Compiling quote v0.6.13
   Compiling pest_meta v2.1.2
   Compiling quote v1.0.2
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling unicase v2.6.0
   Compiling crossbeam-utils v0.7.0
   Compiling time v0.1.42
   Compiling num_cpus v1.12.0
   Compiling iovec v0.1.4
   Compiling net2 v0.2.33
   Compiling atty v0.2.14
   Compiling inotify-sys v0.1.3
   Compiling flate2 v1.0.13
   Compiling filetime v0.2.8
   Compiling clap v2.33.0
   Compiling url v1.7.2
   Compiling url v2.1.1
   Compiling inotify v0.7.0
   Compiling mio v0.6.21
   Compiling crossbeam-channel v0.4.0
   Compiling sass-sys v0.4.17
   Compiling quick-xml v0.17.2
   Compiling regex v1.3.4
   Compiling mio-extras v2.0.6
   Compiling notify v4.0.15
error: failed to run custom build command for `sass-sys v0.4.17`

Caused by:
  process didn't exit successfully: `/build/cobalt/src/cobalt.rs-0.15.9/target/release/build/sass-sys-c31314618974e807/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at ': Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by epage** [comment]
What operating system?  I know building on Windows has been finicky for us.

Also, since the error doesn't contain any context (like what path), could you run with RUST_BACKTRACE so we can try to see why it failed?

**Comment by anthraxx** [comment]
@epage 

This is on Arch Linux and build is in a chroot at `/build/cobalt/src/cobalt.rs-0.15.9/`
```
error: failed to run custom build command for `sass-sys v0.4.17`

Caused by:
  process didn't exit successfully: `/build/cobalt/src/cobalt.rs-0.15.9/target/release/build/sass-sys-c31314618974e807/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at ': Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x564103d31fc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b11b2a23cd910b3
   1:     0x564103d4d69c - core::fmt::write::hca7efce6c0791439
   2:     0x564103d2ef57 - std::io::Write::write_fmt::he56b7f6fb86cf3b5
   3:     0x564103d3403e - std::panicking::default_hook::{{closure}}::hf51e7f0a7424f5cd
   4:     0x564103d33d31 - std::panicking::default_hook::he8ba9c8182908cf7
   5:     0x564103d3466b - std::panicking::rust_panic_with_hook::hf9a08396e191b616
   6:     0x564103d3421e - rust_begin_unwind
   7:     0x564103d4aebe - core::panicking::panic_fmt::h1ec1b70c49f8bf0e
   8:     0x564103d4afb7 - core::result::unwrap_failed::h9d4b97b9a9041349
   9:     0x564103d1c390 - build_script_build::main::h12e400b30823903b
  10:     0x564103d1c953 - std::rt::lang_start::{{closure}}::hc95d917aed2d14d4
  11:     0x564103d34103 - std::panicking::try::do_call::hd0ef6b95899a3d3b
  12:     0x564103d3bbba - __rust_maybe_catch_panic
  13:     0x564103d34b00 - std::rt::lang_start_internal::hd59341531b4fe1e8
  14:     0x564103d1c7d2 - main
  15:     0x7feeda318023 - __libc_start_main
  16:     0x564103d1a0ce - _start
  17:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
```

**Comment by epage** [comment]
Drat, looks like some symbols are messed up due to `--release`.  Could you capture the backtrace without that?

I suspect this is an issue with the chroot not having access to all the commands / libraries needed for building.  I believe this is attempting to build and link against a C library so you'll need basics for builds within the chroot.

**Comment by anthraxx** [comment]
@epage 
No problem, here is one without `--release`, There may of cause be something missing, but the chroot is a build chroot, which means there are quite some build utilities including gcc and tons of other things:
https://www.archlinux.org/groups/x86_64/base-devel/
Plus all the listed dependencies of: https://www.archlinux.org/packages/core/any/base/

```
error: failed to run custom build command for `sass-sys v0.4.17`

Caused by:
  process didn't exit successfully: `/build/cobalt/src/cobalt.rs-0.15.9/target/debug/build/sass-sys-401b02538ded97bc/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at ': Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x5603c4a4d324 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b11b2a23cd910b3
   1:     0x5603c4a68a7c - core::fmt::write::hca7efce6c0791439
   2:     0x5603c4a4a2b7 - std::io::Write::write_fmt::he56b7f6fb86cf3b5
   3:     0x5603c4a4f41e - std::panicking::default_hook::{{closure}}::hf51e7f0a7424f5cd
   4:     0x5603c4a4f111 - std::panicking::default_hook::he8ba9c8182908cf7
   5:     0x5603c4a4fa4b - std::panicking::rust_panic_with_hook::hf9a08396e191b616
   6:     0x5603c4a4f5fe - rust_begin_unwind
   7:     0x5603c4a6629e - core::panicking::panic_fmt::h1ec1b70c49f8bf0e
   8:     0x5603c4a66397 - core::result::unwrap_failed::h9d4b97b9a9041349
   9:     0x5603c4a0bcc8 - core::result::Result<T,E>::expect::h396805c53434a7a5
                               at /build/rust/src/rustc-1.41.0-src/src/libcore/result.rs:983
  10:     0x5603c4a0a3c5 - build_script_build::init_submodule::hb773d69496c39d51
                               at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/sass-sys-0.4.17/build.rs:56
  11:     0x5603c4a0b620 - build_script_build::main::hdbff02e7327d7609
                               at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/sass-sys-0.4.17/build.rs:229
  12:     0x5603c4a0e590 - std::rt::lang_start::{{closure}}::he3e761aa27546bff
                               at /build/rust/src/rustc-1.41.0-src/src/libstd/rt.rs:67
  13:     0x5603c4a4f4e3 - std::panicking::try::do_call::hd0ef6b95899a3d3b
  14:     0x5603c4a56f9a - __rust_maybe_catch_panic
  15:     0x5603c4a4fee0 - std::rt::lang_start_internal::hd59341531b4fe1e8
  16:     0x5603c4a0e569 - std::rt::lang_start::ha034bd4c26a469f7
                               at /build/rust/src/rustc-1.41.0-src/src/libstd/rt.rs:67
  17:     0x5603c4a0b65a - main
  18:     0x7f19a4d7f023 - __libc_start_main
  19:     0x5603c4a090de - _start
  20:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().

```

**Comment by epage** [comment]
Looks like its trying to run git and failing

See https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L55

**Comment by anthraxx** [comment]
Oh wow, didn't find the appropriate github space to look for, stupid me. Thanks for your valuable time, reading a bit further in sass-rs and the linking part I have realized the missing dependency is not really the `git` part, but `libsass` to link against. Thanks a lot and I hope you have an amazing day
